//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET.W._2018.Bey._03.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NET.W._2018.Bey._03.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BaseOfBinaryNumberSystem {
            get {
                return ResourceManager.GetString("BaseOfBinaryNumberSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000000000000000000000000000000000001.
        /// </summary>
        internal static string Epsilon {
            get {
                return ResourceManager.GetString("Epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1023.
        /// </summary>
        internal static string ExponentialBias {
            get {
                return ResourceManager.GetString("ExponentialBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        internal static string MantissaSize {
            get {
                return ResourceManager.GetString("MantissaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0111111111101111111111111111111111111111111111111111111111111111.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111111111101111111111111111111111111111111111111111111111111111.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111111111111000000000000000000000000000000000000000000000000000.
        /// </summary>
        internal static string Nan {
            get {
                return ResourceManager.GetString("Nan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111111111110000000000000000000000000000000000000000000000000000.
        /// </summary>
        internal static string NegativeInfinity {
            get {
                return ResourceManager.GetString("NegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0111111111110000000000000000000000000000000000000000000000000000.
        /// </summary>
        internal static string PositiveInfinity {
            get {
                return ResourceManager.GetString("PositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000000000000000000000000000000000000.
        /// </summary>
        internal static string ZeroValue {
            get {
                return ResourceManager.GetString("ZeroValue", resourceCulture);
            }
        }
    }
}
